# Based on http://conda.pydata.org/docs/travis.html
language: python
sudo: false # use container based build
notifications:
  email: false
branches:
  except:
    - fix-docs

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: CONDA_ENV=py27
    - python: 3.5
      env: CONDA_ENV=py35
    - python: 3.6
      env: CONDA_ENV=py36

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget http://repo.continuum.io/miniconda/Miniconda-3.16.0-Linux-x86_64.sh -O miniconda.sh;
    else
    wget http://repo.continuum.io/miniconda/Miniconda3-3.16.0-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update -q conda
  - conda info -a

install:
  - if [[ "$CONDA_ENV" == "docs" ]]; then
    conda env create -n test_env --file doc/environment.yml;
    else
    conda env create -n test_env --file ci/requirements-$CONDA_ENV.yml;
    fi
  - source activate test_env
  - conda list
  - pip install --no-deps -e .

script:
  - flake8 -j auto xrscipy
  - python -OO -c "import xrscipy"
  - if [[ "$CONDA_ENV" == "docs" ]]; then
    conda install -c conda-forge sphinx_rtd_theme;
    sphinx-build -n -b html -d _build/doctrees doc _build/html;
    else
    py.test xrscipy --cov=xrscipy --cov-config ci/.coveragerc --cov-report term-missing --verbose $EXTRA_FLAGS;
    fi

after_success:
  - coveralls
